### ISSUE TITLE
Définir charte graphique

### ISSUE THREAD

**Issue by JulienParis** [co-demos/BFC-ternum#11]
indiquer ici les codes couleurs, les élements type logos à utiliser et où, etc...

**Comment by JulienParis** [comment]
Est il possible d'avoir ce footer sur un fond bleu #293e86 et écriture en blanc pour faire référence à notre site internet ?

**Comment by jchenrard** [comment]
Pour le pied de page, il faudrait utiliser un fond de couleur #293e86 avec une écriture blanche
Pour les titres de page, il faudrait une typo blanche sur le fonds image : fonds-mediation-1024x384.jpg
Dans l'arborescence et le menu haut, il faudrait utiliser comme couleur de police le bleu #293e86, le turquoise #37bec1 pour indiquer la page où on est et le rouge #f24c61 pour le survol

**Comment by jchenrard** [comment]
**Couleurs**

Les trois couleurs principales utilisées sur le site de MedNum BFC sont : #293e86 (bleu foncé), #f24c61 (rouge) et #37bec1 (turquoise).

**Typographie**

La typo utilisée sur le site de MedNum BFC est Poppins https://fonts.google.com/specimen/Poppins

**URL**

https://cartographie.mednum-bfc.fr/

**Nom pour cette carte**

Cartographie des structures de la médiation numérique en Bourgogne-Franche-Comté

site uniquement en français, pas de version multilingue

**Comment by JulienParis** [comment]
je note cette issue comme fermée et je redispatche les potentielles "mini-issues" dans des issues séparées
