### ISSUE TITLE
définir liste des liens dans le footer

### ISSUE THREAD

**Issue by JulienParis** [co-demos/BFC-ternum#9]

**Comment by jchenrard** [comment]
On va partir sur un footer en 3 colonnes.

1ère colonne : MedNum BFC

Accueil : https://www.mednum-bfc.fr/
Contact : https://www.mednum-bfc.fr/pour-nous-contacter-cest-simple/
A propos : https://www.mednum-bfc.fr/mednum-bfc-la-mission-regionale-pour-la-mediation-numerique/
Nos offres et services : https://mednum-bfc.fr/nos-offres-et-services/

2ème colonne : Nos sites

Le réseau régional des acteurs du numérique : https://humhub.bfc.link/
Numérique & territoires : https://www.numerique-bfc.fr/
Cartographie des structures de la médiation numérique en Bourgogne-Franche-Comté : https://bfc-carto.netlify.com/

3ème colonne : Nos partenaires

GIP Territoires Numériques BFC : http://www.ternum-bfc.fr/
Conseil régional de Bourgogne-Franche-Comté : https://www.bourgognefranchecomte.fr/
Banque des Territoires : https://www.banquedesterritoires.fr/
Mission Société Numérique : https://societenumerique.gouv.fr/
La MedNum : https://lamednum.coop/

**Comment by jchenrard** [comment]
@JulienParis : Est il possible d'avoir ce footer sur un fond bleu #293e86 et écriture en blanc pour faire référence à notre site internet ?

**Comment by JulienParis** [comment]
@jchenrard cette issue étant fermée (mais la laisser qd mm ds le kanban) je rapatrie / copiie-colle ta dernière remarque dans cette issue où on centralisera les questions d'ordre graphisme/couleurs/etc...  : https://github.com/co-demos/BFC-ternum/issues/11
